### ISSUE TITLE
libcore test case compile error

### ISSUE THREAD

**Issue by semihkim** [packetngin/rtos#106]
libcore test case cannot be compiled. It looks dependency of cmocka.

../src/test/cache.c:4:20: fatal error: cmocka.h: No such file or directory
compilation terminated.
core.make:289: recipe for target 'obj/Debug/core/cache1.o' failed
make[3]: *** [obj/Debug/core/cache1.o] Error 1
Kernel.make:48: recipe for target 'core' failed
make[2]: *** [core] Error 2
make[2]: Leaving directory '/home/semih/packetngin'
Build.make:60: recipe for target 'bin/Debug/Build' failed
make[1]: *** [bin/Debug/Build] Error 2
make[1]: Leaving directory '/home/semih/packetngin'
Makefile:11: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by SanggyuLee** [comment]
i modified lib/library.lua yesterday and pushed.
To apply this change, we need to execute premake again as below.

cd rtos; tools/premake5 gmake;

**Comment by semihkim** [comment]
It doesn't work. And the error message is just same.

**Comment by Xeite** [comment]
#105 

should follow intructions described in this commit. Cmoka headers should be installed in standard include path by "make install" command
