### ISSUE TITLE
"is_uint64(str)" can't work without new function strtoull

### ISSUE THREAD

**Issue by siamenock** [packetngin/rtos#246]
at   rtos/lib/ext/src/types.c
is_uint8 ~ is_uint64 functions exist. they use strtol, strtoll functions which can provied signed int64

need strtoull(string to unsigned long long) to make is_uint64 work

**Comment by makerj** [comment]
Assigned to @siamenock

**Comment by makerj** [comment]
Resolved https://github.com/packetngin/rtos/commit/36c6bb4beaf5071ac2f29e85600d32583d5ee8b5
