### ISSUE TITLE
Compile error because of c99, when using gcc 4.8 version

### ISSUE THREAD

**Issue by HyuntaekGurum** [packetngin/rtos#248]
![err](https://user-images.githubusercontent.com/18482361/27850138-621a397c-618d-11e7-8a82-c9e2a9e5c50b.png)

**Comment by HyuntaekGurum** [comment]
commit log hash : 
9a8cb1765155f5f7c15db5ae2b7bfa4d7481aa7e

**Comment by makerj** [comment]
Resolved https://github.com/packetngin/rtos/commit/949c38e1ac0550cfe819aaf6779e268d10d329cd
